/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bibliosystem.Ventanas;
import com.mycompany.bibliosystem.Bitacora;
import com.mycompany.bibliosystem.EscrituraPrestamos;
import com.mycompany.bibliosystem.Estudiante;
import com.mycompany.bibliosystem.Libro;
import com.mycompany.bibliosystem.prestamo;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Pana_Waza
 */
public final class MenuPrestamo extends javax.swing.JFrame {
    
    
    private static String OpB = "Prestamo de libro";
    private static String MoB = "MenuPrestamo";
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrestamo.class.getName());

    /**
     * Creates new form MenuPrestamo
     */
    public MenuPrestamo() {
        initComponents();
        
        int ContadorLibros = Libro.ContadorLibros;
        CargarTabla(com.mycompany.bibliosystem.Libro.libros , ContadorLibros);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        entradaIbn = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ScroollTablaLibros = new javax.swing.JScrollPane();
        TablaLibros = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Libros Disponibles");
        jLabel1.setToolTipText("");

        jLabel2.setText("Ingresar IBN del libro a prestar");

        entradaIbn.addActionListener(this::entradaIbnActionPerformed);

        jButton1.setText("Prestar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Refrescar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        TablaLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Titulo", "Autor", "IBN", "Fecha Publicación", "Ejemplares"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ScroollTablaLibros.setViewportView(TablaLibros);
        if (TablaLibros.getColumnModel().getColumnCount() > 0) {
            TablaLibros.getColumnModel().getColumn(0).setHeaderValue("Titulo");
            TablaLibros.getColumnModel().getColumn(1).setHeaderValue("Autor");
            TablaLibros.getColumnModel().getColumn(2).setHeaderValue("IBN");
            TablaLibros.getColumnModel().getColumn(3).setHeaderValue("Fecha Publicación");
            TablaLibros.getColumnModel().getColumn(4).setHeaderValue("Ejemplares");
        }

        jButton3.setText("Regresar");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ScroollTablaLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(entradaIbn))
                                .addGap(58, 58, 58)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3)
                                .addGap(69, 69, 69)
                                .addComponent(jButton2)
                                .addGap(26, 26, 26))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(ScroollTablaLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entradaIbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entradaIbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaIbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaIbnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // obtener estudiante actual
        // boton prestar
        
        // validar que el libro no este en sus prestamos
        
        int CarnetActual = tres.carnetActual;
        
        String IBN = entradaIbn.getText().trim();
        String Tcarnet = Integer.toString(CarnetActual);
        
        if (prestamo.ConfirmarExistenciPrestamo(CarnetActual, IBN)) {
            JOptionPane.showMessageDialog(this, " NO se puede prestar el libro ya lo ha prestado","Error :",JOptionPane.ERROR_MESSAGE);
        
            Bitacora.appendBitacora(OpB+ " fallido", Tcarnet , MoB);
            return;
        }
        
        initPrestamo(CarnetActual);
    }//GEN-LAST:event_jButton1ActionPerformed

   
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int ContadorLibros = Libro.ContadorLibros;
        CargarTabla(com.mycompany.bibliosystem.Libro.libros , ContadorLibros);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
        MenuUsuario ventana = new MenuUsuario();
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void initPrestamo(int Carnet){
        // obtener ibn
        String IBN = entradaIbn.getText().trim();
        String BookName = Libro.getBookName(IBN);
        
        if (IBN.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tiene ingresar el ibn", "Error : ", JOptionPane.ERROR_MESSAGE);
            String Tcarnet = Integer.toString(Carnet);
            Bitacora.appendBitacora(OpB + " fallido (no se ingreso ibn)", Tcarnet, MoB);
            return;
        }
        
        if (prestamo.BuscarPrestamosVencidos(Carnet)) {
            JOptionPane.showMessageDialog(this, "Tiene prestamos vencidos, tiene que arreglar su situación","Error : ",JOptionPane.ERROR_MESSAGE);
            String Tcarnet = Integer.toString(Carnet);
            Bitacora.appendBitacora(OpB+ " fallido (prestamos vencidos)", Tcarnet , MoB);
            return;
        }
        
        if (!prestamo.CantidadPrestamos(Carnet)) {
            JOptionPane.showMessageDialog(this, "No puede prestar mas de 3 libros","Error : ",JOptionPane.ERROR_MESSAGE);
            String Tcarnet = Integer.toString(Carnet);
            Bitacora.appendBitacora(OpB+ " fallido (quiso prestar mas de 3 libros)", Tcarnet , MoB);
            return;
        }
        
        
        
        if (!Libro.ejemp(IBN)) {
            JOptionPane.showMessageDialog(this, "No hay suficientes ejemplares para prestar el libro","Error : ",JOptionPane.ERROR_MESSAGE);
            String Tcarnet = Integer.toString(Carnet);
            Bitacora.appendBitacora(OpB + " fallido (Ejemplares insuficientes)", Tcarnet, MoB);
            return;
        }
        // metodo para obtener el nombre del libro atraves del ibn
        
        
        if (BookName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se encontro el libro","Error : "+BookName,JOptionPane.ERROR_MESSAGE);
            String Tcarnet = Integer.toString(Carnet);
            Bitacora.appendBitacora(OpB + " fallido (No se encontro el libro)", Tcarnet, MoB);
            return;
        }
        
        
        // obtener fecha actual
        String fechaP = Libro.getDatePrestamo();
            
        // Obtener fecha de devolucion
        String fechaD = Libro.SumaFecha(fechaP);
            
        String historial = "activo";
        
        prestamo.guardarPrestamo(Carnet, IBN, BookName, fechaP, fechaD,historial);
        Estudiante.AgregarPrestamosActivos(Carnet);
            
        String Tcarnet = Integer.toString(Carnet);
        Bitacora.appendBitacora(OpB+ " exitoso ", Tcarnet , MoB);
            
        JOptionPane.showMessageDialog(this, "Se prestó correctamente el libro", "Exito en la operación",JOptionPane.INFORMATION_MESSAGE);
        EscrituraPrestamos.RegistrarPrestamo(Tcarnet, IBN, BookName, fechaP, fechaD, historial);
    }
    
    public void CargarTabla(Libro[] Libros,int ContadorLibros) {
    DefaultTableModel modelo = (DefaultTableModel) TablaLibros.getModel();
    modelo.setRowCount(0); // Limpia la tabla actual

    // Iteramos solo hasta la cantidad de libros realmente guardados
    for (int i = 0; i < ContadorLibros; i++) {
        // Aseguramos que la posición no sea nula por seguridad
        if (Libros[i] != null) {
            Object fila[] = new Object[5];
            fila[0] = Libros[i].getTitulo();
            fila[1] = Libros[i].getAutor();
            fila[2] = Libros[i].getIBN();
            fila[3] = Libros[i].getPublishYear();
            fila[4] = Libros[i].getEjemplares();
            
            modelo.addRow(fila);
        }
    }
}
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        

        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuPrestamo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScroollTablaLibros;
    private javax.swing.JTable TablaLibros;
    private javax.swing.JTextField entradaIbn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    // End of variables declaration//GEN-END:variables
}



