/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bibliosystem.Ventanas;

import com.mycompany.bibliosystem.Bitacora;
import com.mycompany.bibliosystem.EscrituraPrestamos;
import com.mycompany.bibliosystem.Estudiante;
import javax.swing.table.DefaultTableModel;
import com.mycompany.bibliosystem.Libro;
import com.mycompany.bibliosystem.prestamo;
import javax.swing.JOptionPane;

/**
 *
 * @author Pana_Waza
 */
public class RegistroPrestamo extends javax.swing.JFrame {
    
    private static String MoB = "RegistroPrestamo";
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistroPrestamo.class.getName());

    /**
     * Creates new form RegistroPrestamo
     */
    public RegistroPrestamo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Texto1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Texto2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaUsuario = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CarnetTabla = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        entradaIbn = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        jLabel6.setText("Libros Prestados Actualmente ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Asignar Prestamo"));

        jLabel1.setText("Ingresar carnet del usuario");

        Texto1.addActionListener(this::Texto1ActionPerformed);

        jLabel2.setText("Ingresa el ISBN del libro");

        jButton1.setText("Registrar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Texto1)
                    .addComponent(jLabel2)
                    .addComponent(Texto2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Texto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Texto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Devolver Libro"));

        TablaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre del Libro", "IBN", "Fecha Prestamo", "Fecha Devolución", "historial"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaUsuario);

        jButton2.setText("Devolver");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jLabel7.setText("Libros Prestados Actualmente por el estudiante");

        jLabel8.setText("Ingresar carnet del usuario");

        CarnetTabla.addActionListener(this::CarnetTablaActionPerformed);

        jButton3.setText("Ver Prestamos del estudiante");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        entradaIbn.addActionListener(this::entradaIbnActionPerformed);

        jLabel9.setText("Ingresa el ISBN del libro");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CarnetTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(entradaIbn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jButton3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CarnetTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(entradaIbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 3, 36)); // NOI18N
        jLabel5.setText("Menu de Registro de Prestamos");

        jButton4.setText("Salir");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Texto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Texto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Texto1ActionPerformed

    private void CarnetTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarnetTablaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarnetTablaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        // boton buscar
        String carnet = CarnetTabla.getText();
        MostrarDatosTabla(carnet);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        // boton salir

        this.dispose();
        uno Rventana = new uno ();
        Rventana.setLocationRelativeTo(null);
        Rventana.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void entradaIbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaIbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaIbnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        // boton devolver prestamo
        
        devolver();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // boton asignar prestamo
        asignarPrestamo();
    }//GEN-LAST:event_jButton1ActionPerformed

    private boolean esNumerico(String str) {
    if (str == null || str.isEmpty()) {
        return false;
    }
    for (char c : str.toCharArray()) {
        if (!Character.isDigit(c)) {
            return false;
        }
    }
    return true;
}
       
    private void asignarPrestamo() {
    String Tcarnet = Texto1.getText().trim();
    String ibn = Texto2.getText().trim();

    // 1. Validar campos vacíos
    if (Tcarnet.isEmpty() || ibn.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debe llenar todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
        Bitacora.appendBitacora("Asignacion de prestamo fallido (falta de parametros)", Tcarnet , MoB);
        return;
    }

    // 2. Validar que el carnet sea un número (Sin try-catch)
    if (!esNumerico(Tcarnet)) {
        JOptionPane.showMessageDialog(this, "El carnet debe contener solo números", "Error", JOptionPane.ERROR_MESSAGE);
        Bitacora.appendBitacora("Asignacion de prestamo fallido (el carnet tiene letras)", Tcarnet , MoB);
        return;
    }

    int carnet = Integer.parseInt(Tcarnet);
    String bookName = Libro.getBookName(ibn);

    // 3. Validar si el libro existe
    if (bookName == null || bookName.isEmpty()) {
        JOptionPane.showMessageDialog(this, "El ISBN ingresado no existe", "Error", JOptionPane.ERROR_MESSAGE);
        Bitacora.appendBitacora("Asignacion de prestamo fallido (isbn no existe)", Tcarnet , MoB);
        return;
    }

    // 4. Procesar préstamo
    String fechaP = Libro.getDatePrestamo();
    String fechaD = Libro.SumaFecha(fechaP); // Aquí es donde sumas los 15 días

    prestamo.guardarPrestamo(carnet, ibn, bookName, fechaP, fechaD, "activo");
    Libro.RestaEjemplares(ibn);

    String historial = prestamo.getEstadoLibro(carnet, ibn);
    
    JOptionPane.showMessageDialog(this, "Se prestó el libro correctamente", "Operación exitosa", JOptionPane.INFORMATION_MESSAGE);
    Bitacora.appendBitacora("Asignacion de prestamo exitoso", Tcarnet , MoB);
    EscrituraPrestamos.RegistrarPrestamo(Tcarnet, ibn, bookName, fechaP, fechaD, historial);
    
}
    
    private void devolver() {
    // 1. Obtener el índice de la fila seleccionada
    int filaSeleccionada = TablaUsuario.getSelectedRow();
    
    String TextIbn = TablaUsuario.getValueAt(filaSeleccionada, 1).toString();
    String TextCarnet = CarnetTabla.getText().trim();
    

    // 2. Validar que el usuario haya seleccionado una fila
    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Por favor, seleccione un libro de la tabla para devolver.", "Aviso", JOptionPane.WARNING_MESSAGE);
        Bitacora.appendBitacora("Asignacion de prestamo fallido (no se selecciono una fila en la tabla)", TextCarnet , MoB);
        return;
    }
    

    if (TextCarnet.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese el carnet del estudiante primero.", "Error", JOptionPane.ERROR_MESSAGE);
        Bitacora.appendBitacora("Asignacion de prestamo fallido (no se ingreso el carnet )", "vacio" , MoB);
        return;
    }
    
    if (!esNumerico(TextCarnet)) {
        JOptionPane.showMessageDialog(this, "El carnet debe ser numérico.", "Error", JOptionPane.ERROR_MESSAGE);
        Bitacora.appendBitacora("Asignacion de prestamo fallido (el carnet no es numerico)", TextCarnet , MoB);
        return;
    }

    int carnetInt = Integer.parseInt(TextCarnet);

    // 5. Verificar préstamos vencidos (opcional según tu lógica)
    if (prestamo.BuscarPrestamosVencidos(carnetInt)) {
        JOptionPane.showMessageDialog(this, "El estudiante tiene préstamos vencidos.", "Error", JOptionPane.ERROR_MESSAGE);
        Bitacora.appendBitacora("Asignacion de prestamo fallido (El estudiante tiene prestamos vencidos)", TextCarnet , MoB);
        return;
    }

    // 6. Ejecutar la devolución en la "base de datos" (arreglos)
    prestamo.EliminarPrestamo(TextCarnet, TextIbn); // Cambia el estado a "devuelto"
    Libro.SumaEjemplares(TextIbn); // Devuelve el libro al inventario

    JOptionPane.showMessageDialog(this, "Se devolvió el libro correctamente", "Operación exitosa", JOptionPane.INFORMATION_MESSAGE);

    EscrituraPrestamos.EliminarPrestamo(TextCarnet, TextIbn);
    Bitacora.appendBitacora("Asignacion de prestamo exitoso", TextCarnet , MoB);
    // 7. Actualizar la tabla para que el libro desaparezca (porque ya no es "activo")
    MostrarDatosTabla(TextCarnet);
}
    
    
    // ObtenerPrestamos
    private void MostrarDatosTabla(String carnet){
        
        DefaultTableModel modelo = (DefaultTableModel) TablaUsuario.getModel();
        
        modelo.setRowCount(0);
        
        Object[][] fila = prestamo.ObtenerPrestamosActivos(carnet);
        
        Object[] datos = new Object[5];
        
        for (int i = 0; i < 3; i++) {
            if (fila != null ) {
                datos[0] = fila[i][0];
                datos[1] = fila[i][1];
                datos[2] = fila[i][2];
                datos[3] = fila[i][3];
                datos[4] = fila[i][4];
                modelo.addRow(datos);
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegistroPrestamo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CarnetTabla;
    private javax.swing.JTable TablaUsuario;
    private javax.swing.JTextField Texto1;
    private javax.swing.JTextField Texto2;
    private javax.swing.JTextField entradaIbn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
